### ISSUE TITLE
add support for non-EWA backups...

### ISSUE THREAD

**Issue by Vollinger0** [GitHub-TC/EmpyrionWebAccess#22]
I know EWA's mission is to replace EAH, but it would be nice if the tools could be somewhat compatible:

A few points:
1) The backups created from EAH are saved in $egs-installdir\Backup\ 
EWA saves them at $egs-installdir\Saves\Backup
2) EWA requires a defined folder structure and even json files with data from the database to be present in folders, whereas an EAH backup does not have any of that and uses another folder format
3) When creating full backups, even the cache folder is backed up - this can not be used at all for big servers with huge savegames, since that folder grows to several hundred of GBs in a few weeks.

Suggestion:
Please add EAH compatibilty support for EAH's backup "format", so that i can chose an EAH backup from EWA's drop down when i want to restore a structure. Since EAH does not create json files with data from the db, EWA might have to read the entity list from the global.db in the backup.

**Comment by GitHub-TC** [comment]
The EAH is unfortunately not open source, so I can't include support for their features.

The EWA backup functions are also able to backup only the structures. Furthermore EWA has with the functions (Wipe old and unused playfields, Savegame CleanUp) the possibility to keep savegames on a low memory consumption.

Furthermore EWA has the possibility over (Prepare backup (complete)) to "prepare" a backup so that this can be finalized quickly at a server restart.

**Comment by Vollinger0** [comment]
The format is nothing you need the source for, its just the the simple structure of that folder. Oh well, no support for the official backups then, what a pitty. This might reduce the potential audience.

**Comment by GitHub-TC** [comment]
You also need the database with the "old" lifedata which was delivered to the objects via the API.
It is not possible to look directly into the files due to Eleon's internal format.

The EAH also saves its database in the backup and presumably accesses it in the same way as the EWA does with its backups.

Therefore, it is not just another "backup" directory.

**Comment by alecalanis** [comment]
For a backup to be able to be read by EAH to restore stuff, it doesn't need anything else than the actual game data.
Look at how i implemented the backups in ESM (https://github.com/Vollinger0/esm), its just a copy of the gamedata with a certain directory structure.
The structure EWA saves the data differs. I could easily move around files and directories of an EWA backup to make it readable by EAH again, thats all i asked.

**Comment by GitHub-TC** [comment]
Would it be sufficient to specify the root directory for backups?
